In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread("tp.jpg")

print(img.shape)

(1886, 1080, 3)


In [3]:
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

print(gray_img.shape)

(1886, 1080)


In [4]:
img2 = cv2.cvtColor(gray_img,cv2.COLOR_GRAY2BGR)
print(img2.shape)

(1886, 1080, 3)


In [5]:
print(img)

[[[ 69  29  11]
  [ 69  29  11]
  [ 69  29  11]
  ...
  [ 89  34  19]
  [ 89  34  19]
  [ 89  34  19]]

 [[ 69  29  11]
  [ 69  29  11]
  [ 69  29  11]
  ...
  [ 89  34  19]
  [ 89  34  19]
  [ 89  34  19]]

 [[ 69  29  11]
  [ 69  29  11]
  [ 69  29  11]
  ...
  [ 89  34  19]
  [ 89  34  19]
  [ 89  34  19]]

 ...

 [[210 177 162]
  [209 176 161]
  [209 176 161]
  ...
  [188 108  23]
  [188 108  23]
  [188 108  23]]

 [[209 176 161]
  [209 176 161]
  [209 176 161]
  ...
  [188 108  23]
  [188 108  23]
  [188 108  23]]

 [[208 175 160]
  [209 176 161]
  [210 177 162]
  ...
  [188 108  23]
  [188 108  23]
  [188 108  23]]]


In [6]:
print(img2)

[[[ 28  28  28]
  [ 28  28  28]
  [ 28  28  28]
  ...
  [ 36  36  36]
  [ 36  36  36]
  [ 36  36  36]]

 [[ 28  28  28]
  [ 28  28  28]
  [ 28  28  28]
  ...
  [ 36  36  36]
  [ 36  36  36]
  [ 36  36  36]]

 [[ 28  28  28]
  [ 28  28  28]
  [ 28  28  28]
  ...
  [ 36  36  36]
  [ 36  36  36]
  [ 36  36  36]]

 ...

 [[176 176 176]
  [175 175 175]
  [175 175 175]
  ...
  [ 92  92  92]
  [ 92  92  92]
  [ 92  92  92]]

 [[175 175 175]
  [175 175 175]
  [175 175 175]
  ...
  [ 92  92  92]
  [ 92  92  92]
  [ 92  92  92]]

 [[174 174 174]
  [175 175 175]
  [176 176 176]
  ...
  [ 92  92  92]
  [ 92  92  92]
  [ 92  92  92]]]


In [8]:
cv2.imwrite("tp.img2.jpg",img2)
cv2.imwrite("tp.gray_img.jpg",gray_img)


True