In [2]:
import numpy as np
array_zeros = np.zeros((2, 2, 3))

In [3]:
array_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [4]:
array_ones = np.ones((2,3,3))

In [5]:
array_ones.shape

(2, 3, 3)

In [6]:
array_arange = np.arange(10)

In [7]:
array_arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
array_linespace = np.linspace(0,10,5)

In [9]:
array_linespace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])