In [1]:
import numpy as np

In [2]:
vector_a = np.array([1,2,3])

In [6]:
vector_b = np.array([2,3,4])

In [7]:
np.dot(vector_a,vector_b)

20

In [8]:
vector_a.dot(vector_b)

20

In [9]:
np.dot(vector_a,vector_b.T)

20

In [10]:
matrix_a = np.array([[1,2],
                   [3,4]])

In [11]:
matrix_b = np.dot(matrix_a,matrix_a.T)

In [12]:
matrix_b

array([[ 5, 11],
       [11, 25]])

In [13]:
#求范数（默认二范数）
np.linalg.norm([1,2])

2.23606797749979

In [14]:
np.linalg.norm([1,2],1)

3.0

In [15]:
np.linalg.norm([1,2,3,4],np.inf)

4.0

In [16]:
np.linalg.norm([1,2,3,4],-np.inf)

1.0

In [17]:
np.linalg.norm(matrix_b)

29.866369046136157

In [18]:
np.linalg.det(matrix_a)

-2.0000000000000004

In [19]:
np.trace(matrix_a)

5

In [20]:
np.linalg.matrix_rank(matrix_a)

2

In [21]:
vector_a * vector_b

array([ 2,  6, 12])

In [22]:
vector_a ** vector_b

array([ 1,  8, 81], dtype=int32)

In [23]:
np.linalg.pinv(matrix_a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [24]:
np.linalg.inv(matrix_a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])