In [3]:
import numpy as np

In [4]:
np.random.seed()

In [5]:
np.random.randint(1,3,10)

array([1, 1, 1, 2, 2, 2, 2, 2, 2, 2])

In [6]:
2 * np.random.random(10)+1

array([1.5572954 , 1.04735188, 1.08621604, 1.49035636, 2.78316222,
       1.65221409, 2.38665359, 1.41871064, 2.80465166, 1.41306383])

In [7]:
np.random.uniform(1,3,10)

array([1.50295535, 2.74577033, 2.98176715, 2.94091972, 1.75676957,
       2.75037338, 1.91874466, 2.02345542, 2.78664506, 1.08615561])

In [8]:
np.random.normal(size=(4,4))

array([[ 0.25474696,  0.42157739, -1.87107736,  1.60597545],
       [-1.81471543, -1.01361683, -2.19339572,  0.26243863],
       [ 0.59878345,  0.06450017, -3.92262038, -1.10307278],
       [-0.13574311, -1.06445472,  1.51079651, -0.18502365]])

In [9]:
np.random.binomial(n=5,p=0.5,size=10)

array([3, 4, 2, 3, 4, 3, 2, 3, 2, 4])

In [10]:
data = np.arange(10)
np.random.choice(data, 5)

array([9, 6, 2, 5, 0])

In [11]:
np.random.choice(data, 5,replace=False)

array([7, 2, 9, 5, 8])

In [12]:
np.random.permutation(data)

array([4, 2, 0, 1, 9, 6, 8, 5, 3, 7])

In [15]:
np.random.shuffle(data)
print(data)

[1 3 9 7 0 6 2 4 8 5]
