In [1]:
import cv2
import numpy as np

In [2]:
image = cv2.imread("tp.jpg")
image.shape

(1886, 1080, 3)

In [3]:
print(image)

[[[ 69  29  11]
  [ 69  29  11]
  [ 69  29  11]
  ...
  [ 89  34  19]
  [ 89  34  19]
  [ 89  34  19]]

 [[ 69  29  11]
  [ 69  29  11]
  [ 69  29  11]
  ...
  [ 89  34  19]
  [ 89  34  19]
  [ 89  34  19]]

 [[ 69  29  11]
  [ 69  29  11]
  [ 69  29  11]
  ...
  [ 89  34  19]
  [ 89  34  19]
  [ 89  34  19]]

 ...

 [[210 177 162]
  [209 176 161]
  [209 176 161]
  ...
  [188 108  23]
  [188 108  23]
  [188 108  23]]

 [[209 176 161]
  [209 176 161]
  [209 176 161]
  ...
  [188 108  23]
  [188 108  23]
  [188 108  23]]

 [[208 175 160]
  [209 176 161]
  [210 177 162]
  ...
  [188 108  23]
  [188 108  23]
  [188 108  23]]]


In [4]:
cv2.imwrite("tp.bak.jpg",image)


True